version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "${PWD}/mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: secret

  adminer:
    image: adminer
    ports:
      - 8080:8080
